import "./globals.css";
import { Montserrat } from "next/font/google";
import Sidebar from "./components/layout/aside/sidebar";
import Providers from "@/providers";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
const Mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.lang}>
      <ToastContainer />
      <body
        className={
          Mont.className +
          " " +
          "min-h-screen pt-[35px] bg-[#F2F5F8] relative pb-[50px] px-[70px]"
        }
      >
        <main>
          <Providers>
            <div className="fixed left-[70px] top-[25px]">
              <Sidebar params={params} />
            </div>
            <div className="pl-[350px]">{children}</div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
