import "./globals.css";
import { Montserrat } from "next/font/google";
import Sidebar from "./components/layout/aside/sidebar";
import Providers from "@/providers";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { Logo } from "./components/layout/aside/sidebar/logo";

import { getDictionary } from "../../../getDictionary";
const Mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const lang = await getDictionary(params.lang);
  return (
    <html lang={lang}>
      <body
        className={
          Mont.className +
          " " +
          "min-h-screen pt-[35px] pb-[50px] px-[20px] md:px-[70px] bg-[#F2F5F8] relative"
        }
      >
        <ToastContainer />
        <main>
          <Providers>
            <div className="md:mb-[12px] ml-[5px] md:fixed">
              <Logo />
            </div>
            <div className="absolute left-0 right-0 bottom-0 md:fixed md:left-[70px] md:top-[100px] ">
              <Sidebar lang={lang} />
            </div>
            <div className="md:pl-[350px]">{children}</div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
